### ISSUE TITLE
How to use that? What does it do?

### ISSUE THREAD

**Issue by pacid** [AccordGroup/MandrillSwiftMailerBundle#12]
Hi, any info of how can I use this bundle to make sth work would be appreciated.

**Comment by Kyoushu** [comment]
When installed, this bundle will use [Mandrill](https://mandrillapp.com) to deliver emails when the "mailer" service is used.

Installation instructions can be found in [README.md](https://github.com/AccordGroup/MandrillSwiftMailerBundle/blob/master/README.md)
