### ISSUE TITLE
Compatibility with Symfony 3.0?

### ISSUE THREAD

**Issue by bibeksigdel33** [AccordGroup/MandrillSwiftMailerBundle#13]
Is this bundle compatible with symfony3.0 ?

**Comment by Rattler3** [comment]
I personally have not tested this on Symfony 3x yet. However I see no reason why this will not work, will try and test tomorrow and get back to you.

**Comment by Antiseptikk** [comment]
This bundle was tested with symfony 3 and i create pull request to fix yaml incompatibility. You can see https://github.com/AccordGroup/MandrillSwiftMailerBundle/pull/18

**Comment by Rattler3** [comment]
Closing as fixed in PR #14
