### ISSUE TITLE
Create a 1.3.0 version with "Async option"

### ISSUE THREAD

**Issue by Remiii** [AccordGroup/MandrillSwiftMailerBundle#17]

**Comment by Kyoushu** [comment]
We do plan on adding this, but it'll be a little while until we can work on it.

**Comment by Remiii** [comment]
@Kyoushu I use allready this in production. :sunglasses:

**Comment by Kyoushu** [comment]
I noticed, nice to see other people using our stuff. I'll duplicate your implementation when I get some time.

**Comment by Kyoushu** [comment]
1.2.1 has been released, which includes the async options. Sorry about the delay.
