### ISSUE TITLE
Symfony 3.0 stable version

### ISSUE THREAD

**Issue by snamor** [AccordGroup/MandrillSwiftMailerBundle#19]
I've been trying the bundle in it's master branch with symfony 3.0 and it works as expected. May you release a stable version for the package at its current state?

Thank you!

**Comment by dgiovanon** [comment]
I've Symfony3.0 and I change in vendor\accord\mandrill-swiftmailer-bundle\Accord\MandrillSwiftMailerBundle\Resources\config\services.yml

this

**arguments:
            - @swiftmailer.transport.eventdispatcher.accord_mandrill**

for this

**arguments: ['@swiftmailer.transport.eventdispatcher.accord_mandrill']**

The bundle works perfectly!

**Comment by snamor** [comment]
@dgiovanon using master instead of 1.2 solves all issues. That is why we need a new stable build. Please @Kyoushu ! 🙏

**Comment by Kyoushu** [comment]
Sorry about that, kept meaning to sort this out, 1.2.1 has been released
