### ISSUE TITLE
Symfony 4.2 stable version

### ISSUE THREAD

**Issue by Taylix** [AccordGroup/MandrillSwiftMailerBundle#26]
You have handle Symfony 4.2 deprecation, but not release new version.
When do you plan to do it?

**Comment by jrattue** [comment]
@Taylix I have tagged a new release.

**Comment by Taylix** [comment]
Obviously, the release is not push on packagist:
https://packagist.org/packages/accord/mandrill-swiftmailer-bundle

Same issue with our private packagist, I try to add manually your package, but last release is 1.3.0 

Have you already have this issue?

**Comment by jrattue** [comment]
@Taylix I have re-setup the packagist -> github sync. The new version should appear shortly.

**Comment by Taylix** [comment]
Thanks !
