### ISSUE TITLE
Please separate logic from framework wrapping 

### ISSUE THREAD

**Issue by RemiWoler** [AccordGroup/MandrillSwiftMailerBundle#9]
As this seems to be the most complete and maintained library for this functionally, I believe it would be helpful to separate the logic into a framework-agnostic library, which the Symfony2 bundle could depend on. For Symfony2, this will provide the same functionality because of Composer (the bundle can require the lib), while for every other framework the library now becomes available to use, without the (unneeded) Symfony2 wrapping.

**Comment by verschoof** [comment]
:+1:

**Comment by Kyoushu** [comment]
I've been thinking about doing this for a while. I'll try to get started on it this week and keep you updated.

**Comment by verschoof** [comment]
Well, if you make a new branch we can do some PR's? :)

**Comment by Kyoushu** [comment]
A new repo will be made to contain just the transport and related tests. This will be under the namespace Accord\MandrillSwiftMailer.

The existing class Accord\MandrillSwiftMailerBundle\SwiftMailer\MandrillTransport will effectively become a proxy for the transport loaded from the new repo. This will ensure BC compatibility for people using the bundle just for the transport class, if there are any.

This update will be released as 1.2.0 when it's done, so I've created the branch 1.2.x-dev.

**Comment by Kyoushu** [comment]
I'll annotate mark the old transport as deprecated

**Comment by Rattler3** [comment]
:+1:

**Comment by Kyoushu** [comment]
The standalone transport can now be found here, it's also registered in Packagist. I've also taken the opportunity to shore up the unit tests.

https://github.com/AccordGroup/MandrillSwiftMailer

I'll create a 1.0.0 release for the library when the 1.2.x-dev branch is ready to be merged back into master.

**Comment by Kyoushu** [comment]
All done, 1.2.0+ released

**Comment by verschoof** [comment]
Good job!

**Comment by RemiWoler** [comment]
Awesome work! This is much appreciated!
